### ISSUE TITLE
No module named Lazypredict.Supervised

### ISSUE THREAD

**Issue by SSMK-wq** [shankarpandala/lazypredict#392]
**Describe the bug**
Unable to import the Lazy predict Regressor

**To Reproduce**
1. import lazypredict
2. from lazypredict.Supervised import LazyRegressor   # throws error in this line as shown below

**Expected behavior**
Lazy Regressor should be imported successfully

**Screenshots**
See below

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Version 0.2.12
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [9], in <cell line: 27>()
     26 import lazypredict
---> 27 from lazypredict.Supervised import *
     28 from sklearn.linear_model import *

ModuleNotFoundError: No module named 'lazypredict.Supervised'
```

**Comment by kushagrathisside** [comment]
Hi @SSMK-wq ! I checked this issue but could not find this error. This probably is due to improper importing of the library.
If this issue has been solved, please mark close the issue.
![Colab file](https://user-images.githubusercontent.com/76547274/208724459-3ea293d7-130e-4d38-9ee9-0d8a8a4abf6e.jpeg)

**Comment by JavadMAlizadeh** [comment]
@kushagrathisside
You will notice the problem if you run your code. For example:

from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X = data.data
y= data.target

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=.5,random_state =123)

clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

**Comment by JavadMAlizadeh** [comment]
Here is the error:

Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.7.0
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
runfile('C:/Program Files/JetBrains/Pycharm/Temple/Machine_Learning/Lazy_Predict/lazypredict.py', wdir='C:/Program Files/JetBrains/Pycharm/Temple/Machine_Learning/Lazy_Predict')
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-946ab3e92068>", line 1, in <module>
    runfile('C:/Program Files/JetBrains/Pycharm/Temple/Machine_Learning/Lazy_Predict/lazypredict.py', wdir='C:/Program Files/JetBrains/Pycharm/Temple/Machine_Learning/Lazy_Predict')
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Program Files/JetBrains/Pycharm/Temple/Machine_Learning/Lazy_Predict/lazypredict.py", line 1, in <module>
    from lazypredict.Supervised import LazyClassifier
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Program Files\JetBrains\Pycharm\Temple\Machine_Learning\Lazy_Predict\lazypredict.py", line 1, in <module>
    from lazypredict.Supervised import LazyClassifier
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'lazypredict.Supervised'; 'lazypredict' is not a package

**Comment by shankarpandala** [comment]
This is a naming conflict - you named your script 'lazypredict.py' which conflicts with the library import. Rename your script to something else (e.g., 'my_test.py' or 'lazy_test.py') and it will work. This is a common Python issue when script names match library names.
