### ISSUE TITLE
NameError: name 'LazyRegressor' is not defined

### ISSUE THREAD

**Issue by nosacapital** [shankarpandala/lazypredict#402]
I am using Python 3.9.13 and the installation of the lazypredict library went smoothly. I then tried out the regression example  got the following: 

Traceback (most recent call last):
  File "/Users/user/Documents/CrunchDao/test.py", line 1, in <module>
    from lazypredict.Supervised import LazyRegressor
  File "/Users/user/Documents/CrunchDao/lazypredict.py", line 36, in <module>
    reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
NameError: name 'LazyRegressor' is not defined

Are there any solutions to this? It seems others are using this library with ease. Please help. Thanks

**Comment by shankarpandala** [comment]
The error shows you named your script 'lazypredict.py' which conflicts with the library import. Rename your script to something else (e.g., 'my_regression.py') and the import will work correctly.
